"""Auto-generated migration

Revision ID: 2241cad13bfc
Revises: 43f024a3b24e
Create Date: 2023-11-27 11:39:01.176013

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2241cad13bfc"
down_revision: Union[str, None] = "43f024a3b24e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
