"""Auto-generated migration

Revision ID: 231dc734d665
Revises: 738109225592
Create Date: 2023-11-27 03:33:12.167163

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "231dc734d665"
down_revision: Union[str, None] = "738109225592"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "administrator_system_metadata_id_fkey", "administrator", type_="foreignkey"
    )
    op.drop_column("administrator", "system_metadata_id")
    op.create_foreign_key(
        None, "system_metadata", "administrator", ["administrator_id"], ["ID"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "system_metadata", type_="foreignkey")
    op.add_column(
        "administrator",
        sa.Column(
            "system_metadata_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "administrator_system_metadata_id_fkey",
        "administrator",
        "system_metadata",
        ["system_metadata_id"],
        ["ID"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
