"""Auto-generated migration

Revision ID: 7d29afa5ef7b
Revises: 2241cad13bfc
Create Date: 2023-11-27 11:41:09.937620

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d29afa5ef7b"
down_revision: Union[str, None] = "2241cad13bfc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
