"""Auto-generated migration

Revision ID: 8a973944ea4b
Revises: c375d3cc1e5b
Create Date: 2023-11-27 11:45:14.172875

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a973944ea4b"
down_revision: Union[str, None] = "c375d3cc1e5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
