"""initial

Revision ID: 738109225592
Revises: 
Create Date: 2023-11-01 07:12:24.716088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '738109225592'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('coefficient', sa.Float(), nullable=False),
    sa.Column('change_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('system_metadata',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('trade_union_contribution', sa.BigInteger(), nullable=False),
    sa.Column('income_tax', sa.BigInteger(), nullable=False),
    sa.Column('minimum_salary', sa.BigInteger(), nullable=False),
    sa.Column('pension_contribution', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('administrator',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=15), nullable=False),
    sa.Column('system_metadata_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['system_metadata_id'], ['system_metadata.ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('position',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('employee',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=True),
    sa.Column('administrator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrator_id'], ['administrator.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('employee_position',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['position.ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employee_id', 'position_id')
    )
    op.create_table('payment_history',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=12), nullable=False),
    sa.Column('earnings', sa.BigInteger(), nullable=False),
    sa.Column('payments', sa.BigInteger(), nullable=False),
    sa.Column('deductions', sa.BigInteger(), nullable=False),
    sa.Column('employee_od', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_od'], ['employee.ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_history')
    op.drop_table('employee_position')
    op.drop_table('employee')
    op.drop_table('position')
    op.drop_table('administrator')
    op.drop_table('system_metadata')
    op.drop_table('category')
    # ### end Alembic commands ###
